# Generated by Django 3.1 on 2020-09-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200924_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
