# Generated by Django 3.1 on 2020-09-26 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200926_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
