# Generated by Django 3.1 on 2020-09-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
